# Generated by Django 4.0.1 on 2022-01-14 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.book', verbose_name='book'),
        ),
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='booking',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.subcategory', verbose_name='subcategory'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='achievements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.achievement', verbose_name='achievements'),
        ),
    ]
