# Generated by Django 4.0.1 on 2022-01-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='seen'),
        ),
    ]
